modLoader="javafml"
# Forge for 1.19 is version 41
loaderVersion="[41,)"
license="All rights reserved"
issueTrackerURL=""
showAsResourcePack=false

[[mods]]
    modId="mod"
    version="1.0.0.0"
    displayName="Ben Mod"
    updateJSONURL=""
    displayURL=""
    logoFile=""
    credits=""
    authors=""
    description='''
Ben mod Ben mod!
    '''
    displayTest="MATCH_VERSION"

[[dependencies.benmod]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.benmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"